// @generated by tools/generator from the selected flighthq-bitmap API; do not edit.
#![forbid(unsafe_code)]

use flighthq_bitmap::{
    apply_bitmap_curve as apply_surface_curve, apply_bitmap_levels as apply_surface_levels,
    apply_bitmap_palette_map as apply_surface_palette_map,
    build_bitmap_brightness_color_matrix as build_surface_brightness_color_matrix,
    build_bitmap_contrast_color_matrix as build_surface_contrast_color_matrix,
    build_bitmap_grayscale_color_matrix as build_surface_grayscale_color_matrix,
    build_bitmap_hue_rotation_color_matrix as build_surface_hue_rotation_color_matrix,
    build_bitmap_invert_color_matrix as build_surface_invert_color_matrix,
    build_bitmap_saturation_color_matrix as build_surface_saturation_color_matrix,
    build_bitmap_sepia_color_matrix as build_surface_sepia_color_matrix,
    color_matrix_bitmap as color_matrix_surface,
    compare_bitmap_fingerprints as compare_surface_fingerprints,
    concat_bitmap_color_matrix as concat_surface_color_matrix,
    convolve_bitmap as convolve_surface, copy_bitmap_alpha as copy_surface_alpha,
    copy_bitmap_pixels as copy_surface_pixels,
    create_bitmap_fingerprint as create_surface_fingerprint, dilate_bitmap as dilate_surface,
    erode_bitmap as erode_surface, fill_bitmap_noise as fill_surface_noise,
    fill_bitmap_perlin_noise as fill_surface_perlin_noise,
    fill_bitmap_rectangle as fill_surface_rectangle,
    fill_bitmap_turbulence as fill_surface_turbulence,
    get_bitmap_color_bounds_rectangle as get_surface_color_bounds_rectangle,
    get_bitmap_coverage as get_surface_coverage,
    get_bitmap_histogram as get_surface_histogram,
    get_bitmap_mismatch as get_surface_mismatch,
    merge_bitmap_channels as merge_surface_channels,
    multiply_bitmap_alpha as multiply_surface_alpha, pixelate_bitmap as pixelate_surface,
    premultiply_bitmap_pixels as premultiply_surface_pixels,
    set_bitmap_alpha as set_surface_alpha,
    set_bitmap_color_matrix_identity as set_surface_color_matrix_identity,
    unpremultiply_bitmap_pixels as unpremultiply_surface_pixels,
};
use flighthq_types::{
    Bitmap as Surface, BitmapConvolutionOptions as SurfaceConvolutionOptions,
    BitmapFingerprint as SurfaceFingerprint, BitmapRegion as SurfaceRegion, OpaqueHostValue,
};
use wasm_bindgen::prelude::*;

fn surface(data: &[u8], width: f64, height: f64) -> Surface {
    Surface {
        __flight_identity: std::sync::Arc::new(()),
        __flight_entity_runtime: Default::default(),
        alpha_type: "straight".to_owned(),
        data: data.to_vec(),
        format: "rgba8unorm".to_owned(),
        gamut: "srgb".to_owned(),
        height,
        kind: OpaqueHostValue::String("bitmap".to_owned()),
        version: 0.0,
        width,
        ..Default::default()
    }
}

fn region(data: &[u8], descriptor: &[f64]) -> SurfaceRegion {
    assert_eq!(
        descriptor.len(),
        6,
        "surface region descriptor must contain [surfaceWidth, surfaceHeight, x, y, width, height]",
    );
    SurfaceRegion {
        __flight_identity: std::sync::Arc::new(()),
        bitmap: surface(data, descriptor[0], descriptor[1]),
        x: descriptor[2],
        y: descriptor[3],
        width: descriptor[4],
        height: descriptor[5],
    }
}

fn fingerprint(cells: &[u8], grid_size: f64) -> SurfaceFingerprint {
    SurfaceFingerprint {
        __flight_identity: std::sync::Arc::new(()),
        cells: cells.to_vec(),
        grid_size,
    }
}

fn copy_u8_output(out: &mut [u8], owned: &[u8]) {
    assert_eq!(out.len(), owned.len(), "generated surface output changed length");
    out.copy_from_slice(owned);
}

fn copy_f64_output(out: &mut [f64], owned: &[f64]) {
    assert_eq!(out.len(), owned.len(), "generated matrix output changed length");
    out.copy_from_slice(owned);
}

fn optional_channel_map(values: &[f64]) -> Option<Vec<f64>> {
    (!values.is_empty()).then(|| values.to_vec())
}

fn optional_byte_channel_map(values: &[u8]) -> Option<Vec<u8>> {
    (!values.is_empty()).then(|| values.to_vec())
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn apply_surface_curve_wasm(
    dest_data: &mut [u8],
    dest_descriptor: &[f64],
    source_data: &[u8],
    source_descriptor: &[f64],
    red_lut: &[u8],
    green_lut: &[u8],
    blue_lut: &[u8],
    alpha_lut: &[u8],
) {
    let mut dest = region(dest_data, dest_descriptor);
    let source = region(source_data, source_descriptor);
    apply_surface_curve(
        &mut dest,
        &source,
        optional_byte_channel_map(red_lut),
        optional_byte_channel_map(green_lut),
        optional_byte_channel_map(blue_lut),
        optional_byte_channel_map(alpha_lut),
    );
    copy_u8_output(dest_data, &dest.bitmap.data);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn apply_surface_levels_wasm(
    dest_data: &mut [u8],
    dest_descriptor: &[f64],
    source_data: &[u8],
    source_descriptor: &[f64],
    black_point: f64,
    white_point: f64,
    gamma: f64,
) {
    let mut dest = region(dest_data, dest_descriptor);
    let source = region(source_data, source_descriptor);
    apply_surface_levels(
        &mut dest,
        &source,
        Some(black_point),
        Some(white_point),
        Some(gamma),
    );
    copy_u8_output(dest_data, &dest.bitmap.data);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn apply_surface_palette_map_wasm(
    dest_data: &mut [u8],
    dest_descriptor: &[f64],
    source_data: &[u8],
    source_descriptor: &[f64],
    red_map: &[f64],
    green_map: &[f64],
    blue_map: &[f64],
    alpha_map: &[f64],
) {
    let mut dest = region(dest_data, dest_descriptor);
    let source = region(source_data, source_descriptor);
    apply_surface_palette_map(
        &mut dest,
        &source,
        optional_channel_map(red_map),
        optional_channel_map(green_map),
        optional_channel_map(blue_map),
        optional_channel_map(alpha_map),
    );
    copy_u8_output(dest_data, &dest.bitmap.data);
}

#[wasm_bindgen]
pub fn build_surface_brightness_color_matrix_wasm(out: &mut [f64], amount: f64) {
    let mut owned = out.to_vec();
    build_surface_brightness_color_matrix(&mut owned, amount);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn build_surface_contrast_color_matrix_wasm(out: &mut [f64], amount: f64) {
    let mut owned = out.to_vec();
    build_surface_contrast_color_matrix(&mut owned, amount);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn build_surface_grayscale_color_matrix_wasm(out: &mut [f64]) {
    let mut owned = out.to_vec();
    build_surface_grayscale_color_matrix(&mut owned);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn build_surface_hue_rotation_color_matrix_wasm(out: &mut [f64], degrees: f64) {
    let mut owned = out.to_vec();
    build_surface_hue_rotation_color_matrix(&mut owned, degrees);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn build_surface_invert_color_matrix_wasm(out: &mut [f64]) {
    let mut owned = out.to_vec();
    build_surface_invert_color_matrix(&mut owned);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn build_surface_saturation_color_matrix_wasm(out: &mut [f64], amount: f64) {
    let mut owned = out.to_vec();
    build_surface_saturation_color_matrix(&mut owned, amount);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn build_surface_sepia_color_matrix_wasm(out: &mut [f64]) {
    let mut owned = out.to_vec();
    build_surface_sepia_color_matrix(&mut owned);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn set_surface_color_matrix_identity_wasm(out: &mut [f64]) {
    let mut owned = out.to_vec();
    set_surface_color_matrix_identity(&mut owned);
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn concat_surface_color_matrix_wasm(out: &mut [f64], first: &[f64], second: &[f64]) {
    let mut owned = out.to_vec();
    concat_surface_color_matrix(&mut owned, &first.to_vec(), &second.to_vec());
    copy_f64_output(out, &owned);
}

#[wasm_bindgen]
pub fn color_matrix_surface_wasm(
    out: &mut [u8],
    source_data: &[u8],
    source_descriptor: &[f64],
    matrix: &[f64],
) {
    let mut owned = out.to_vec();
    let source = region(source_data, source_descriptor);
    color_matrix_surface(&mut owned, &source, &matrix.to_vec());
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn compare_surface_fingerprints_wasm(
    first_cells: &[u8],
    first_grid_size: f64,
    second_cells: &[u8],
    second_grid_size: f64,
) -> f64 {
    compare_surface_fingerprints(
        &fingerprint(first_cells, first_grid_size),
        &fingerprint(second_cells, second_grid_size),
    )
}

#[wasm_bindgen]
pub fn create_surface_fingerprint_wasm(
    out: &mut [u8],
    source_data: &[u8],
    source_width: f64,
    source_height: f64,
    grid_size: f64,
) {
    let result = create_surface_fingerprint(
        &surface(source_data, source_width, source_height),
        Some(grid_size),
    );
    copy_u8_output(out, &result.cells);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn convolve_surface_wasm(
    out: &mut [u8],
    source_data: &[u8],
    source_descriptor: &[f64],
    matrix: &[f64],
    matrix_x: f64,
    matrix_y: f64,
    bias: f64,
    edge: String,
    divisor: f64,
    preserve_alpha: bool,
) {
    let mut owned = out.to_vec();
    let source = region(source_data, source_descriptor);
    let options = SurfaceConvolutionOptions {
        __flight_identity: std::sync::Arc::new(()),
        bias: Some(bias),
        edge: Some(edge),
        divisor: if divisor.is_nan() {
            None
        } else {
            Some(divisor)
        },
        matrix: matrix.to_vec(),
        matrix_x,
        matrix_y,
        preserve_alpha: Some(preserve_alpha),
    };
    convolve_surface(&mut owned, &source, &options);
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn copy_surface_pixels_wasm(
    dest_data: &mut [u8],
    dest_descriptor: &[f64],
    source_data: &[u8],
    source_descriptor: &[f64],
    composite: bool,
) {
    let mut dest = region(dest_data, dest_descriptor);
    let source = region(source_data, source_descriptor);
    copy_surface_pixels(&mut dest, &source, Some(composite));
    copy_u8_output(dest_data, &dest.bitmap.data);
}

#[wasm_bindgen]
pub fn copy_surface_alpha_wasm(
    dest_data: &mut [u8],
    dest_descriptor: &[f64],
    source_data: &[u8],
    source_descriptor: &[f64],
) {
    let mut dest = region(dest_data, dest_descriptor);
    let source = region(source_data, source_descriptor);
    copy_surface_alpha(&mut dest, &source);
    copy_u8_output(dest_data, &dest.bitmap.data);
}

#[wasm_bindgen]
pub fn multiply_surface_alpha_wasm(data: &mut [u8], descriptor: &[f64], factor: f64) {
    let mut target = region(data, descriptor);
    multiply_surface_alpha(&mut target, factor);
    copy_u8_output(data, &target.bitmap.data);
}

#[wasm_bindgen]
pub fn set_surface_alpha_wasm(data: &mut [u8], descriptor: &[f64], alpha: f64) {
    let mut target = region(data, descriptor);
    set_surface_alpha(&mut target, alpha);
    copy_u8_output(data, &target.bitmap.data);
}

#[wasm_bindgen]
pub fn fill_surface_rectangle_wasm(data: &mut [u8], descriptor: &[f64], color: f64) {
    let mut target = region(data, descriptor);
    fill_surface_rectangle(&mut target, color);
    copy_u8_output(data, &target.bitmap.data);
}

#[wasm_bindgen]
pub fn fill_surface_noise_wasm(
    data: &mut [u8],
    descriptor: &[f64],
    seed: f64,
    low: f64,
    high: f64,
    gray_scale: bool,
) {
    let mut target = region(data, descriptor);
    fill_surface_noise(&mut target, seed, Some(low), Some(high), Some(gray_scale));
    copy_u8_output(data, &target.bitmap.data);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn fill_surface_perlin_noise_wasm(
    data: &mut [u8],
    descriptor: &[f64],
    base_x: f64,
    base_y: f64,
    octaves: f64,
    seed: f64,
    gray_scale: bool,
    stitch: bool,
    channel_options: f64,
) {
    let mut target = region(data, descriptor);
    fill_surface_perlin_noise(
        &mut target,
        base_x,
        base_y,
        octaves,
        seed,
        Some(gray_scale),
        Some(stitch),
        Some(channel_options),
    );
    copy_u8_output(data, &target.bitmap.data);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn fill_surface_turbulence_wasm(
    data: &mut [u8],
    descriptor: &[f64],
    base_x: f64,
    base_y: f64,
    octaves: f64,
    seed: f64,
    gray_scale: bool,
    stitch: bool,
    channel_options: f64,
) {
    let mut target = region(data, descriptor);
    fill_surface_turbulence(
        &mut target,
        base_x,
        base_y,
        octaves,
        seed,
        Some(gray_scale),
        Some(stitch),
        Some(channel_options),
    );
    copy_u8_output(data, &target.bitmap.data);
}

#[wasm_bindgen]
pub fn dilate_surface_wasm(out: &mut [u8], source_data: &[u8], source_descriptor: &[f64], radius: f64) {
    let mut owned = out.to_vec();
    let source = region(source_data, source_descriptor);
    dilate_surface(&mut owned, &source, radius);
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn erode_surface_wasm(out: &mut [u8], source_data: &[u8], source_descriptor: &[f64], radius: f64) {
    let mut owned = out.to_vec();
    let source = region(source_data, source_descriptor);
    erode_surface(&mut owned, &source, radius);
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn pixelate_surface_wasm(
    out: &mut [u8],
    source_data: &[u8],
    source_descriptor: &[f64],
    block_size: f64,
) {
    let mut owned = out.to_vec();
    let source = region(source_data, source_descriptor);
    pixelate_surface(&mut owned, &source, block_size);
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn premultiply_surface_pixels_wasm(out: &mut [u8], source: &[u8], length: f64) {
    let mut owned = out.to_vec();
    premultiply_surface_pixels(&mut owned, &source.to_vec(), length);
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn unpremultiply_surface_pixels_wasm(out: &mut [u8], source: &[u8], length: f64) {
    let mut owned = out.to_vec();
    unpremultiply_surface_pixels(&mut owned, &source.to_vec(), length);
    copy_u8_output(out, &owned);
}

#[wasm_bindgen]
pub fn get_surface_coverage_wasm(
    data: &[u8],
    width: f64,
    height: f64,
    background_color: f64,
    channel_tolerance: f64,
) -> f64 {
    get_surface_coverage(
        &surface(data, width, height),
        background_color,
        Some(channel_tolerance),
    )
}

#[wasm_bindgen]
pub fn get_surface_color_bounds_rectangle_wasm(
    out: &mut [f64],
    data: &[u8],
    descriptor: &[f64],
    mask: f64,
    color: f64,
    find_color: bool,
) -> bool {
    assert_eq!(out.len(), 4, "rectangle output must contain four values");
    let Some(rectangle) =
        get_surface_color_bounds_rectangle(&region(data, descriptor), mask, color, Some(find_color))
    else {
        return false;
    };
    out.copy_from_slice(&[
        rectangle.x,
        rectangle.y,
        rectangle.width,
        rectangle.height,
    ]);
    true
}

#[wasm_bindgen]
pub fn get_surface_histogram_wasm(out: &mut [f64], data: &[u8], descriptor: &[f64]) {
    assert_eq!(out.len(), 1024, "histogram output must contain four 256-bin channels");
    let histogram = get_surface_histogram(&region(data, descriptor));
    out[0..256].copy_from_slice(&histogram.red);
    out[256..512].copy_from_slice(&histogram.green);
    out[512..768].copy_from_slice(&histogram.blue);
    out[768..1024].copy_from_slice(&histogram.alpha);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn get_surface_mismatch_wasm(
    out: &mut [f64],
    source_data: &[u8],
    source_width: f64,
    source_height: f64,
    other_data: &[u8],
    other_width: f64,
    other_height: f64,
    channel_tolerance: f64,
) {
    assert_eq!(out.len(), 4, "mismatch output must contain four metrics");
    let mismatch = get_surface_mismatch(
        &surface(source_data, source_width, source_height),
        &surface(other_data, other_width, other_height),
        Some(channel_tolerance),
    );
    out.copy_from_slice(&[
        mismatch.mismatched_pixels,
        mismatch.total_pixels,
        mismatch.fraction,
        mismatch.max_channel_delta,
    ]);
}

#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn merge_surface_channels_wasm(
    out_data: &mut [u8],
    out_descriptor: &[f64],
    red_data: &[u8],
    red_descriptor: &[f64],
    green_data: &[u8],
    green_descriptor: &[f64],
    blue_data: &[u8],
    blue_descriptor: &[f64],
    alpha_data: &[u8],
    alpha_descriptor: &[f64],
) {
    let mut out = region(out_data, out_descriptor);
    let red = region(red_data, red_descriptor);
    let green = region(green_data, green_descriptor);
    let blue = region(blue_data, blue_descriptor);
    let alpha = region(alpha_data, alpha_descriptor);
    merge_surface_channels(&mut out, &red, &green, &blue, &alpha);
    copy_u8_output(out_data, &out.bitmap.data);
}
