import { writeFileSync } from 'node:fs';

import { convolveBitmap, createBitmap } from '@flighthq/bitmap';

// Generates a differential fixture for `crates/flighthq-bitmap-core`: inputs plus the bytes UPSTREAM'S OWN
// TypeScript produces for them. The Rust mirror then has an oracle it did not author, over far more of the input
// space than upstream's nine hand-written cases reach — random matrices, every edge mode, offset regions,
// fractional divisors and biases, both `preserveAlpha` settings.
//
// This is the mirror discipline applied to fixtures: the expected bytes come from the implementation being
// mirrored, so a disagreement is a defect in the port by construction and cannot be argued away.
it('writes the convolution differential fixture', { timeout: 300_000 }, () => {
  // A deterministic PRNG, so the fixture is reproducible and reviewable rather than a different file each run.
  let seed = 0x2f6e2b1;
  const next = (): number => {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    return seed / 0x7fffffff;
  };

  const edges = ['clamp', 'transparent', 'wrap', 'mirror'] as const;
  const cases: string[] = [];
  for (let index = 0; index < 48; index++) {
    const width = 1 + Math.floor(next() * 9);
    const height = 1 + Math.floor(next() * 9);
    const bitmap = createBitmap(width, height);
    for (let i = 0; i < bitmap.data.length; i++) bitmap.data[i] = Math.floor(next() * 256);

    const matrixX = 1 + 2 * Math.floor(next() * 3);
    const matrixY = 1 + 2 * Math.floor(next() * 3);
    // Weights include negatives and fractions, which is where rounding and clamping actually get exercised.
    const matrix = Array.from({ length: matrixX * matrixY }, () => Math.round((next() * 4 - 1.5) * 100) / 100);
    const edge = edges[Math.floor(next() * edges.length)]!;
    const preserveAlpha = next() < 0.5;
    // A third of cases take the implicit divisor (the weight sum), and one in six an explicit zero.
    const divisorRoll = next();
    const divisor = divisorRoll < 0.34 ? undefined : divisorRoll < 0.5 ? 0 : Math.round((next() * 6 - 1) * 100) / 100;
    const bias = Math.round((next() * 40 - 20) * 100) / 100;

    const x = Math.floor(next() * width);
    const y = Math.floor(next() * height);
    const regionWidth = Math.max(1, Math.floor(next() * (width - x + 1)));
    const regionHeight = Math.max(1, Math.floor(next() * (height - y + 1)));

    const out = new Uint8ClampedArray(regionWidth * regionHeight * 4);
    const options = {
      bias,
      edge,
      matrix,
      matrixX,
      matrixY,
      preserveAlpha,
      ...(divisor === undefined ? {} : { divisor }),
    };
    convolveBitmap(out, { bitmap, x, y, width: regionWidth, height: regionHeight }, options);

    // One line per case, `;`-separated fields, so the Rust side parses it with `split` and the crate keeps
    // its zero dependencies. A JSON fixture would have cost it a `serde` dev-dependency to read 48 records.
    cases.push(
      [
        width,
        height,
        x,
        y,
        regionWidth,
        regionHeight,
        matrixX,
        matrixY,
        divisor === undefined ? '-' : divisor,
        bias,
        edge,
        preserveAlpha ? 1 : 0,
        [...bitmap.data].join(','),
        matrix.join(','),
        [...out].join(','),
      ].join(';'),
    );
  }

  writeFileSync(
    '../../crates/flighthq-bitmap-core/tests/convolution-fixture.txt',
    "# Generated by packages/bitmap-wasm/src/fixturegen.bench.test.ts from UPSTREAM's convolveBitmap.\n" +
      '# bitmapWidth;bitmapHeight;x;y;width;height;matrixX;matrixY;divisor|-;bias;edge;preserveAlpha;data;matrix;expected\n' +
      cases.join('\n') +
      '\n',
  );
  expect(cases.length).toBe(48);
});
