import { writeFileSync } from 'node:fs';

import {
  createBitmap,
  dilateBitmap,
  erodeBitmap,
  multiplyBitmapAlpha,
  pixelateBitmap,
  setBitmapAlpha,
} from '@flighthq/bitmap';

// Differential fixtures for the alpha, morphological and pixelate mirrors in `crates/flighthq-bitmap-core`,
// with the expected bytes produced by UPSTREAM'S OWN TypeScript. Same discipline as the convolution fixture:
// the oracle is the implementation being mirrored, so a disagreement is a defect in the port by construction.
//
// These reach cases upstream's hand-written suite does not: regions offset and hanging off the bitmap edge,
// radii and block sizes that leave partial windows, and random RGBA rather than single-channel ramps.
it('writes the alpha, morphological and pixelate differential fixtures', { timeout: 300_000 }, () => {
  let seed = 0x51f3c7d;
  const next = (): number => {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    return seed / 0x7fffffff;
  };
  const randomBitmap = (width: number, height: number) => {
    const bitmap = createBitmap(width, height);
    for (let i = 0; i < bitmap.data.length; i++) bitmap.data[i] = Math.floor(next() * 256);
    return bitmap;
  };

  const lines: string[] = [];
  for (let index = 0; index < 60; index++) {
    const width = 1 + Math.floor(next() * 7);
    const height = 1 + Math.floor(next() * 7);
    // Regions that start inside but may extend past the edge, which is where the clipping differs per kernel.
    const x = Math.floor(next() * width);
    const y = Math.floor(next() * height);
    const regionWidth = Math.max(1, Math.floor(next() * (width + 1)));
    const regionHeight = Math.max(1, Math.floor(next() * (height + 1)));
    const kind = ['setAlpha', 'multiplyAlpha', 'dilate', 'erode', 'pixelate'][index % 5]!;
    const source = randomBitmap(width, height);
    const before = [...source.data];
    const region = { bitmap: source, x, y, width: regionWidth, height: regionHeight };

    let parameter: number;
    let expected: number[];
    if (kind === 'setAlpha' || kind === 'multiplyAlpha') {
      // In-place kernels: the expectation is the whole bitmap afterwards.
      // Fractional as well as out-of-range, because rounding is where `setBitmapAlpha` can differ: a plain
      // truncating cast agrees with `Math.round` on every integer and disagrees on 128.7.
      parameter = kind === 'setAlpha' ? Math.round(next() * 30000) / 100 - 20 : Math.round(next() * 150) / 100;
      if (kind === 'setAlpha') setBitmapAlpha(region, parameter);
      else multiplyBitmapAlpha(region, parameter);
      expected = [...source.data];
    } else {
      // Out-of-place kernels: the expectation is the region-sized output buffer.
      const out = new Uint8ClampedArray(regionWidth * regionHeight * 4);
      parameter = kind === 'pixelate' ? Math.floor(next() * 5) : Math.floor(next() * 4) - 1;
      if (kind === 'dilate') dilateBitmap(out, region, parameter);
      else if (kind === 'erode') erodeBitmap(out, region, parameter);
      else pixelateBitmap(out, region, parameter);
      expected = [...out];
    }

    lines.push(
      [kind, width, height, x, y, regionWidth, regionHeight, parameter, before.join(','), expected.join(',')].join(';'),
    );
  }

  writeFileSync(
    '../../crates/flighthq-bitmap-core/tests/kernel-fixture.txt',
    '# Generated by packages/bitmap-wasm/src/fixturegen2.bench.test.ts from UPSTREAM kernels.\n' +
      '# kind;bitmapWidth;bitmapHeight;x;y;width;height;parameter;dataBefore;expected\n' +
      lines.join('\n') +
      '\n',
  );
  expect(lines.length).toBe(60);
});
