export const FLIGHT_TASK_RUNTIME_CRATE = 'flighthq-runtime';

export function emitFlightTaskRuntimeManifest(): string {
  return [
    '# @generated compiler runtime; do not edit.',
    '[package]',
    `name = "${FLIGHT_TASK_RUNTIME_CRATE}"`,
    'version = "0.1.0"',
    'edition = "2024"',
    'license = "MIT"',
    'publish = false',
    '',
    '[lib]',
    'path = "src/lib.rs"',
    '',
  ].join('\n');
}

export function emitFlightTaskRuntime(): string {
  return String.raw`// @generated by tools/generator; do not edit.
#![forbid(unsafe_code)]

use std::collections::VecDeque;
use std::future::{poll_fn, Future};
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::task::{Context, Poll, Wake, Waker};

#[derive(Clone, Debug, PartialEq)]
pub enum FlightValue {
    Undefined,
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Array(Vec<FlightValue>),
    Record(Vec<(String, FlightValue)>),
    Error {
        name: String,
        message: String,
        stack: Option<String>,
        cause: Option<Box<FlightValue>>,
    },
    Function,
    Symbol,
    Object,
}

impl Default for FlightValue {
    fn default() -> Self {
        Self::Undefined
    }
}

/// Compatibility name for generated boundaries whose TypeScript type remains unrecovered.
pub type OpaqueHostValue = FlightValue;

/// Canonical storage for TypeScript unions shared across generated crate boundaries.
#[derive(Clone, Debug, PartialEq)]
pub enum FlightUnion2<A, B> {
    A(A),
    B(B),
}

impl<A: std::fmt::Display, B: std::fmt::Display> std::fmt::Display for FlightUnion2<A, B> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::A(value) => value.fmt(formatter),
            Self::B(value) => value.fmt(formatter),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FlightJsonError {
    OpaqueHostObject,
}

impl std::fmt::Display for FlightJsonError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::OpaqueHostObject => formatter.write_str("an opaque host object cannot be serialized as portable JSON"),
        }
    }
}

impl std::error::Error for FlightJsonError {}

pub fn flight_json_stringify(value: &FlightValue) -> Result<Option<String>, FlightJsonError> {
    flight_json_fragment(value)
}

pub fn flight_value_to_string(value: &FlightValue) -> String {
    match value {
        FlightValue::Undefined => "undefined".to_owned(),
        FlightValue::Null => "null".to_owned(),
        FlightValue::Bool(value) => value.to_string(),
        FlightValue::Number(value) if value.is_nan() => "NaN".to_owned(),
        FlightValue::Number(value) if *value == f64::INFINITY => "Infinity".to_owned(),
        FlightValue::Number(value) if *value == f64::NEG_INFINITY => "-Infinity".to_owned(),
        FlightValue::Number(value) => flight_json_number(*value),
        FlightValue::String(value) => value.clone(),
        FlightValue::Array(values) => values
            .iter()
            .map(|value| match value {
                FlightValue::Undefined | FlightValue::Null => String::new(),
                value => flight_value_to_string(value),
            })
            .collect::<Vec<_>>()
            .join(","),
        FlightValue::Record(_) | FlightValue::Object => "[object Object]".to_owned(),
        FlightValue::Error { name, message, .. } => match (name.is_empty(), message.is_empty()) {
            (true, _) => message.clone(),
            (_, true) => name.clone(),
            (false, false) => format!("{name}: {message}"),
        },
        FlightValue::Function => "function".to_owned(),
        FlightValue::Symbol => "Symbol()".to_owned(),
    }
}

fn flight_json_fragment(value: &FlightValue) -> Result<Option<String>, FlightJsonError> {
    match value {
        FlightValue::Undefined | FlightValue::Function | FlightValue::Symbol => Ok(None),
        FlightValue::Null => Ok(Some("null".to_owned())),
        FlightValue::Bool(value) => Ok(Some(value.to_string())),
        FlightValue::Number(value) => Ok(Some(flight_json_number(*value))),
        FlightValue::String(value) => Ok(Some(flight_json_quote(value))),
        FlightValue::Array(values) => {
            let items = values
                .iter()
                .map(|value| flight_json_fragment(value).map(|value| value.unwrap_or_else(|| "null".to_owned())))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(Some(format!("[{}]", items.join(","))))
        }
        FlightValue::Record(values) => {
            let mut properties: Vec<(&str, &FlightValue)> = Vec::new();
            for (key, value) in values {
                if let Some((_, previous)) = properties.iter_mut().find(|(previous, _)| previous == &key.as_str()) {
                    *previous = value;
                } else {
                    properties.push((key, value));
                }
            }
            let fields = properties
                .into_iter()
                .filter_map(|(key, value)| match flight_json_fragment(value) {
                    Ok(Some(value)) => Some(Ok(format!("{}:{}", flight_json_quote(key), value))),
                    Ok(None) => None,
                    Err(error) => Some(Err(error)),
                })
                .collect::<Result<Vec<_>, _>>()?;
            Ok(Some(format!("{{{}}}", fields.join(","))))
        }
        FlightValue::Error { .. } | FlightValue::Object => Err(FlightJsonError::OpaqueHostObject),
    }
}

fn flight_json_number(value: f64) -> String {
    if !value.is_finite() {
        return "null".to_owned();
    }
    if value == 0.0_f64 {
        return "0".to_owned();
    }
    let magnitude = value.abs();
    if !(1.0e-6_f64..1.0e21_f64).contains(&magnitude) {
        let scientific = format!("{value:e}");
        let (significand, exponent) = scientific
            .split_once('e')
            .expect("Rust scientific number formatting must contain an exponent");
        return if exponent.starts_with('-') {
            scientific
        } else {
            format!("{significand}e+{exponent}")
        };
    }
    value.to_string()
}

fn flight_json_quote(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len() + 2);
    escaped.push('"');
    for character in value.chars() {
        match character {
            '"' => escaped.push_str("\\\""),
            '\\' => escaped.push_str("\\\\"),
            character if character == char::from(8) => escaped.push_str("\\b"),
            character if character == char::from(9) => escaped.push_str("\\t"),
            character if character == char::from(10) => escaped.push_str("\\n"),
            character if character == char::from(12) => escaped.push_str("\\f"),
            character if character == char::from(13) => escaped.push_str("\\r"),
            character if character <= char::from(31) => escaped.push_str(&format!("\\u{:04x}", character as u32)),
            character => escaped.push(character),
        }
    }
    escaped.push('"');
    escaped
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FlightTaskOrigin {
    pub package: &'static str,
    pub source: &'static str,
    pub line: u32,
    pub column: u32,
    pub lexical_path: &'static str,
    pub fingerprint: &'static str,
}

#[derive(Clone, Debug, PartialEq)]
pub enum FlightRejection {
    Null,
    Bool(bool),
    Number(f64),
    String(String),
    Error { name: String, message: String },
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FlightHostUnavailable {
    pub capability: String,
    pub origin: FlightTaskOrigin,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FlightRuntimeUnavailable {
    pub origin: FlightTaskOrigin,
}

#[derive(Clone, Debug, PartialEq)]
pub enum FlightTaskError {
    Rejection(FlightRejection),
    HostUnavailable(FlightHostUnavailable),
    RuntimeUnavailable(FlightRuntimeUnavailable),
}

pub type FlightTaskOutcome<T> = Result<T, FlightTaskError>;

struct FlightTaskState<T> {
    driver: Option<Arc<dyn RunnableFlightTask>>,
    observers: Vec<Waker>,
    outcome: Option<FlightTaskOutcome<T>>,
}

impl<T> Default for FlightTaskState<T> {
    fn default() -> Self {
        Self { driver: None, observers: Vec::new(), outcome: None }
    }
}

pub struct FlightTask<T> {
    shared: Arc<Mutex<FlightTaskState<T>>>,
    yielded: bool,
}

impl<T> Clone for FlightTask<T> {
    fn clone(&self) -> Self {
        Self { shared: self.shared.clone(), yielded: false }
    }
}

impl<T> FlightTask<T> {
    pub fn ready(value: T, _origin: FlightTaskOrigin) -> Self {
        Self::settled(Ok(value))
    }

    pub fn reject(rejection: FlightRejection, _origin: FlightTaskOrigin) -> Self {
        Self::settled(Err(FlightTaskError::Rejection(rejection)))
    }

    pub fn host_unavailable(capability: impl Into<String>, origin: FlightTaskOrigin) -> Self {
        Self::settled(Err(FlightTaskError::HostUnavailable(FlightHostUnavailable {
            capability: capability.into(),
            origin,
        })))
    }

    fn settled(outcome: FlightTaskOutcome<T>) -> Self {
        Self {
            shared: Arc::new(Mutex::new(FlightTaskState {
                driver: None,
                observers: Vec::new(),
                outcome: Some(outcome),
            })),
            yielded: false,
        }
    }
}

impl<T> FlightTask<T>
where
    T: Clone + Send + 'static,
{
    pub fn start<Work>(work: Work, origin: FlightTaskOrigin) -> Self
    where
        Work: Future<Output = FlightTaskOutcome<T>> + Send + 'static,
    {
        let shared = Arc::new(Mutex::new(FlightTaskState::default()));
        let driver = Arc::new(FlightTaskDriver {
            future: Mutex::new(Some(Box::pin(work))),
            origin,
            queued: AtomicBool::new(false),
            shared: shared.clone(),
        });
        shared.lock().unwrap().driver = Some(driver.clone());
        let pending = driver.poll_once().is_pending();
        if pending && flight_task_scheduler().is_none() {
            driver.settle(Err(FlightTaskError::RuntimeUnavailable(
                FlightRuntimeUnavailable { origin },
            )));
        }
        Self { shared, yielded: false }
    }

    /// Joins a homogeneous task collection without serializing observation by input order.
    /// Input tasks have already started eagerly; polling every unsettled handle in each turn
    /// preserves result order while allowing any observed error to settle the join immediately.
    pub fn all(tasks: Vec<Self>, origin: FlightTaskOrigin) -> FlightTask<Vec<T>> {
        let mut tasks = tasks.into_iter().map(Some).collect::<Vec<_>>();
        let mut outputs = vec![None; tasks.len()];
        let mut remaining = tasks.len();
        FlightTask::start(
            async move {
                poll_fn(move |context| {
                    for index in 0..tasks.len() {
                        let Some(task) = tasks[index].as_mut() else { continue; };
                        match Pin::new(task).poll(context) {
                            Poll::Ready(Ok(value)) => {
                                outputs[index] = Some(value);
                                tasks[index] = None;
                                remaining -= 1;
                            }
                            Poll::Ready(Err(error)) => return Poll::Ready(Err(error)),
                            Poll::Pending => {}
                        }
                    }
                    if remaining != 0 {
                        return Poll::Pending;
                    }
                    Poll::Ready(Ok(outputs
                        .iter_mut()
                        .map(|output| output.take().expect("completed taskAll slot must contain output"))
                        .collect()))
                })
                .await
            },
            origin,
        )
    }
}

const DYNAMIC_HOST_TASK_ORIGIN: FlightTaskOrigin = FlightTaskOrigin {
    package: "@flighthq/runtime",
    source: "generated/runtime/host-task",
    line: 0,
    column: 0,
    lexical_path: "dynamic-host-task",
    fingerprint: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
};

/// Typed fallback for a task supplied by a host capability that is unavailable natively.
/// The task settles as an error without requiring or fabricating an output value.
pub fn host_task<T>(capability: impl Into<String>) -> FlightTask<T> {
    FlightTask::host_unavailable(capability, DYNAMIC_HOST_TASK_ORIGIN)
}

impl<T> Future for FlightTask<T>
where
    T: Clone + Send + 'static,
{
    type Output = FlightTaskOutcome<T>;

    fn poll(mut self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<Self::Output> {
        if !self.yielded {
            self.yielded = true;
            context.waker().wake_by_ref();
            return Poll::Pending;
        }
        let mut state = self.shared.lock().unwrap();
        if let Some(outcome) = &state.outcome {
            return Poll::Ready(outcome.clone());
        }
        if !state.observers.iter().any(|observer| observer.will_wake(context.waker())) {
            state.observers.push(context.waker().clone());
        }
        Poll::Pending
    }
}

trait RunnableFlightTask: Send + Sync {
    fn run(self: Arc<Self>);
}

struct FlightTaskDriver<T> {
    future: Mutex<Option<Pin<Box<dyn Future<Output = FlightTaskOutcome<T>> + Send + 'static>>>>,
    origin: FlightTaskOrigin,
    queued: AtomicBool,
    shared: Arc<Mutex<FlightTaskState<T>>>,
}

impl<T> FlightTaskDriver<T>
where
    T: Clone + Send + 'static,
{
    fn poll_once(self: &Arc<Self>) -> Poll<()> {
        let waker = Waker::from(self.clone());
        let mut context = Context::from_waker(&waker);
        let outcome = {
            let mut future_slot = self.future.lock().unwrap();
            let Some(future) = future_slot.as_mut() else { return Poll::Ready(()); };
            match future.as_mut().poll(&mut context) {
                Poll::Ready(outcome) => {
                    *future_slot = None;
                    Some(outcome)
                }
                Poll::Pending => None,
            }
        };
        if let Some(outcome) = outcome {
            self.settle(outcome);
            Poll::Ready(())
        } else {
            Poll::Pending
        }
    }

    fn schedule(self: &Arc<Self>) {
        if self.queued.swap(true, Ordering::AcqRel) {
            return;
        }
        let Some(scheduler) = flight_task_scheduler() else {
            self.queued.store(false, Ordering::Release);
            self.settle(Err(FlightTaskError::RuntimeUnavailable(
                FlightRuntimeUnavailable { origin: self.origin },
            )));
            return;
        };
        scheduler.schedule(ScheduledFlightTask { task: self.clone() });
    }

    fn settle(&self, outcome: FlightTaskOutcome<T>) {
        let observers = {
            let mut state = self.shared.lock().unwrap();
            if state.outcome.is_some() {
                return;
            }
            state.outcome = Some(outcome);
            state.driver = None;
            std::mem::take(&mut state.observers)
        };
        for observer in observers {
            observer.wake();
        }
    }
}

impl<T> RunnableFlightTask for FlightTaskDriver<T>
where
    T: Clone + Send + 'static,
{
    fn run(self: Arc<Self>) {
        self.queued.store(false, Ordering::Release);
        let _ = self.poll_once();
    }
}

impl<T> Wake for FlightTaskDriver<T>
where
    T: Clone + Send + 'static,
{
    fn wake(self: Arc<Self>) {
        self.schedule();
    }

    fn wake_by_ref(self: &Arc<Self>) {
        self.schedule();
    }
}

#[derive(Clone)]
pub struct ScheduledFlightTask {
    task: Arc<dyn RunnableFlightTask>,
}

impl ScheduledFlightTask {
    pub fn run(self) {
        self.task.run();
    }
}

pub trait FlightTaskScheduler: Send + Sync {
    /// Enqueue the task for a later turn. Implementations must not poll it inline.
    fn schedule(&self, task: ScheduledFlightTask);
}

static FLIGHT_TASK_SCHEDULER: OnceLock<Arc<dyn FlightTaskScheduler>> = OnceLock::new();

pub fn install_flight_task_scheduler<Scheduler>(scheduler: Scheduler) -> Result<(), &'static str>
where
    Scheduler: FlightTaskScheduler + 'static,
{
    FLIGHT_TASK_SCHEDULER
        .set(Arc::new(scheduler))
        .map_err(|_| "Flight task scheduler was already installed")
}

fn flight_task_scheduler() -> Option<&'static Arc<dyn FlightTaskScheduler>> {
    FLIGHT_TASK_SCHEDULER.get()
}

#[derive(Clone, Default)]
pub struct DeterministicFlightTaskScheduler {
    queue: Arc<Mutex<VecDeque<ScheduledFlightTask>>>,
}

impl DeterministicFlightTaskScheduler {
    pub fn run_until_idle(&self) {
        loop {
            let task = self.queue.lock().unwrap().pop_front();
            let Some(task) = task else { break; };
            task.run();
        }
    }

    pub fn block_on<T>(&self, mut task: FlightTask<T>) -> FlightTaskOutcome<T>
    where
        T: Clone + Send + 'static,
    {
        let wake = Arc::new(DeterministicObserverWake { awake: AtomicBool::new(true) });
        let waker = Waker::from(wake.clone());
        let mut context = Context::from_waker(&waker);
        loop {
            wake.awake.store(false, Ordering::Release);
            if let Poll::Ready(outcome) = Pin::new(&mut task).poll(&mut context) {
                return outcome;
            }
            self.run_until_idle();
            if !wake.awake.load(Ordering::Acquire) && self.queue.lock().unwrap().is_empty() {
                panic!("deterministic Flight task stalled without a wake");
            }
        }
    }
}

impl FlightTaskScheduler for DeterministicFlightTaskScheduler {
    fn schedule(&self, task: ScheduledFlightTask) {
        self.queue.lock().unwrap().push_back(task);
    }
}

struct DeterministicObserverWake {
    awake: AtomicBool,
}

impl Wake for DeterministicObserverWake {
    fn wake(self: Arc<Self>) {
        self.awake.store(true, Ordering::Release);
    }

    fn wake_by_ref(self: &Arc<Self>) {
        self.awake.store(true, Ordering::Release);
    }
}

static DETERMINISTIC_FLIGHT_TASK_SCHEDULER: OnceLock<DeterministicFlightTaskScheduler> = OnceLock::new();

pub fn install_deterministic_flight_task_scheduler() -> DeterministicFlightTaskScheduler {
    let scheduler = DETERMINISTIC_FLIGHT_TASK_SCHEDULER
        .get_or_init(DeterministicFlightTaskScheduler::default)
        .clone();
    let _ = FLIGHT_TASK_SCHEDULER.set(Arc::new(scheduler.clone()));
    scheduler
}

pub struct FlightTaskYield {
    yielded: bool,
}

impl Future for FlightTaskYield {
    type Output = ();

    fn poll(mut self: Pin<&mut Self>, context: &mut Context<'_>) -> Poll<()> {
        if self.yielded {
            Poll::Ready(())
        } else {
            self.yielded = true;
            context.waker().wake_by_ref();
            Poll::Pending
        }
    }
}

pub fn flight_task_yield() -> FlightTaskYield {
    FlightTaskYield { yielded: false }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::AtomicUsize;

    const ORIGIN: FlightTaskOrigin = FlightTaskOrigin {
        package: "@flighthq/runtime-fixture",
        source: "generated/runtime-fixture.rs",
        line: 1,
        column: 1,
        lexical_path: "fixture",
        fingerprint: "sha256:0000000000000000000000000000000000000000000000000000000000000000",
    };

    #[test]
    fn serializes_recursive_portable_values_with_javascript_container_semantics() {
        let value = FlightValue::Record(vec![
            (String::from("first"), FlightValue::Number(1.0_f64)),
            (String::from("omitted"), FlightValue::Undefined),
            (
                String::from("nested"),
                FlightValue::Record(vec![(
                    String::from("quoted\"key"),
                    FlightValue::String(String::from("line\nfeed")),
                )]),
            ),
            (
                String::from("array"),
                FlightValue::Array(vec![
                    FlightValue::Undefined,
                    FlightValue::Number(f64::NAN),
                    FlightValue::Function,
                ]),
            ),
            (String::from("first"), FlightValue::String(String::from("last"))),
        ]);
        assert_eq!(
            flight_json_stringify(&value),
            Ok(Some(String::from(
                "{\"first\":\"last\",\"nested\":{\"quoted\\\"key\":\"line\\nfeed\"},\"array\":[null,null,null]}"
            )))
        );
        assert_eq!(flight_json_stringify(&FlightValue::Undefined), Ok(None));
        assert_eq!(
            flight_json_stringify(&FlightValue::Object),
            Err(FlightJsonError::OpaqueHostObject)
        );
        assert_eq!(
            flight_json_stringify(&FlightValue::Error {
                name: String::from("TypeError"),
                message: String::from("invalid value"),
                stack: None,
                cause: None,
            }),
            Err(FlightJsonError::OpaqueHostObject)
        );
    }

    #[test]
    fn formats_json_numbers_at_ecmascript_decimal_boundaries() {
        let value = FlightValue::Array(vec![
            FlightValue::Number(-0.0_f64),
            FlightValue::Number(1.0e-7_f64),
            FlightValue::Number(1.0e-6_f64),
            FlightValue::Number(1.0e20_f64),
            FlightValue::Number(1.0e21_f64),
            FlightValue::Number(1.23e-7_f64),
        ]);
        assert_eq!(
            flight_json_stringify(&value),
            Ok(Some(String::from(
                "[0,1e-7,0.000001,100000000000000000000,1e+21,1.23e-7]",
            ))),
        );
    }

    #[test]
    fn stringifies_portable_values_with_javascript_coercion_semantics() {
        assert_eq!(flight_value_to_string(&FlightValue::Undefined), "undefined");
        assert_eq!(flight_value_to_string(&FlightValue::Number(f64::NAN)), "NaN");
        assert_eq!(
            flight_value_to_string(&FlightValue::Array(vec![
                FlightValue::String("first".to_owned()),
                FlightValue::Null,
                FlightValue::Number(2.0_f64),
            ])),
            "first,,2",
        );
        assert_eq!(
            flight_value_to_string(&FlightValue::Error {
                name: "TypeError".to_owned(),
                message: "invalid".to_owned(),
                stack: None,
                cause: None,
            }),
            "TypeError: invalid",
        );
    }

    #[test]
    fn preserves_eager_prefix_and_mandatory_yield() {
        let scheduler = install_deterministic_flight_task_scheduler();
        let prefix = Arc::new(AtomicUsize::new(0));
        let observed = prefix.clone();
        let task = FlightTask::start(
            async move {
                observed.fetch_add(1, Ordering::SeqCst);
                flight_task_yield().await;
                Ok(7_u32)
            },
            ORIGIN,
        );
        assert_eq!(prefix.load(Ordering::SeqCst), 1, "prefix runs before start returns");

        let ready = FlightTask::ready(9_u32, ORIGIN);
        let wake = Arc::new(DeterministicObserverWake { awake: AtomicBool::new(false) });
        let waker = Waker::from(wake);
        let mut context = Context::from_waker(&waker);
        let mut ready = Box::pin(ready);
        assert!(ready.as_mut().poll(&mut context).is_pending(), "ready observation still yields");
        assert_eq!(ready.as_mut().poll(&mut context), Poll::Ready(Ok(9)));
        assert_eq!(scheduler.block_on(task), Ok(7));
    }

    #[test]
    fn executes_once_for_multiple_observers() {
        let scheduler = install_deterministic_flight_task_scheduler();
        let executions = Arc::new(AtomicUsize::new(0));
        let observed = executions.clone();
        let task = FlightTask::start(
            async move {
                observed.fetch_add(1, Ordering::SeqCst);
                flight_task_yield().await;
                Ok(String::from("settled"))
            },
            ORIGIN,
        );
        let second = task.clone();
        assert_eq!(scheduler.block_on(task), Ok(String::from("settled")));
        assert_eq!(scheduler.block_on(second), Ok(String::from("settled")));
        assert_eq!(executions.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn owns_input_after_the_caller_drops_it() {
        let scheduler = install_deterministic_flight_task_scheduler();
        fn length_after_yield(input: &str) -> FlightTask<usize> {
            let owned = input.to_owned();
            FlightTask::start(
                async move {
                    flight_task_yield().await;
                    Ok(owned.len())
                },
                ORIGIN,
            )
        }
        let source = String::from("owned across suspension");
        let task = length_after_yield(&source);
        drop(source);
        assert_eq!(scheduler.block_on(task), Ok(23));
    }

    #[test]
    fn preserves_typed_rejection() {
        let scheduler = install_deterministic_flight_task_scheduler();
        let task = FlightTask::<bool>::reject(FlightRejection::String(String::from("nope")), ORIGIN);
        assert_eq!(
            scheduler.block_on(task),
            Err(FlightTaskError::Rejection(FlightRejection::String(String::from("nope"))))
        );
    }

    #[test]
    fn task_all_preserves_input_order_across_different_completion_turns() {
        let scheduler = install_deterministic_flight_task_scheduler();
        assert_eq!(
            scheduler.block_on(FlightTask::<String>::all(Vec::new(), ORIGIN)),
            Ok(Vec::new())
        );
        let slow_first = FlightTask::start(
            async move {
                flight_task_yield().await;
                Ok(String::from("first"))
            },
            ORIGIN,
        );
        let ready_second = FlightTask::ready(String::from("second"), ORIGIN);
        assert_eq!(
            scheduler.block_on(FlightTask::all(vec![slow_first, ready_second], ORIGIN)),
            Ok(vec![String::from("first"), String::from("second")])
        );
    }

    #[test]
    fn task_all_observes_a_later_error_without_waiting_for_an_earlier_slot() {
        let scheduler = install_deterministic_flight_task_scheduler();
        let never = FlightTask::start(
            async move {
                std::future::pending::<()>().await;
                Ok(1_u32)
            },
            ORIGIN,
        );
        let rejected = FlightTask::<u32>::reject(
            FlightRejection::String(String::from("later slot rejected")),
            ORIGIN,
        );
        assert_eq!(
            scheduler.block_on(FlightTask::all(vec![never, rejected], ORIGIN)),
            Err(FlightTaskError::Rejection(FlightRejection::String(String::from(
                "later slot rejected"
            ))))
        );
    }

    #[test]
    fn represents_unavailable_host_tasks_without_default_output() {
        #[derive(Clone, Debug, PartialEq)]
        struct NoDefault;

        let scheduler = install_deterministic_flight_task_scheduler();
        let task = host_task::<NoDefault>("host.then");
        assert_eq!(
            scheduler.block_on(task),
            Err(FlightTaskError::HostUnavailable(FlightHostUnavailable {
                capability: String::from("host.then"),
                origin: DYNAMIC_HOST_TASK_ORIGIN,
            }))
        );
    }
}
`;
}
