//! Replays convolution cases whose expected bytes were produced by UPSTREAM'S OWN TypeScript.
//!
//! `crates/flighthq-bitmap-core` is a mirror, so its oracle has to be the thing it mirrors. The unit tests in
//! the crate carry upstream's nine hand-written cases; this carries forty-eight generated ones, reaching the
//! parts of the input space those nine do not: random matrices with negative and fractional weights, every edge
//! mode, offset sub-regions, an implicit divisor and an explicit zero, and both `preserveAlpha` settings.
//!
//! The fixture is regenerated by `packages/bitmap-wasm/src/fixturegen.bench.test.ts`, which calls upstream
//! directly. Its PRNG is seeded, so the file is stable and a diff to it is reviewable rather than noise.
//!
//! A disagreement here is a defect in the port by construction — there is no interpretation in which the mirror
//! is right and the mirrored implementation is wrong.
//!
//! Measured worth, rather than assumed: swapping two colour channels in the accumulation loop passes ALL ELEVEN
//! of upstream's own hand-written cases and is caught only here. Those cases mostly use single-channel ramps or
//! uniform fills, where a green/blue mix-up is invisible; the random RGBA data in this fixture is not.

use flighthq_bitmap_core::{EdgeMode, RegionView, convolve_bitmap};

struct Case {
    bitmap_width: i32,
    bitmap_height: i32,
    x: i32,
    y: i32,
    width: i32,
    height: i32,
    matrix_x: i32,
    matrix_y: i32,
    divisor: Option<f64>,
    bias: f64,
    edge: EdgeMode,
    preserve_alpha: bool,
    data: Vec<u8>,
    matrix: Vec<f64>,
    expected: Vec<u8>,
}

fn numbers<T, F: Fn(&str) -> T>(field: &str, parse: F) -> Vec<T> {
    field.split(',').map(|value| parse(value)).collect()
}

fn parse(line: &str) -> Case {
    let f: Vec<&str> = line.split(';').collect();
    assert_eq!(f.len(), 15, "fixture line has 15 fields: {line}");
    Case {
        bitmap_width: f[0].parse().unwrap(),
        bitmap_height: f[1].parse().unwrap(),
        x: f[2].parse().unwrap(),
        y: f[3].parse().unwrap(),
        width: f[4].parse().unwrap(),
        height: f[5].parse().unwrap(),
        matrix_x: f[6].parse().unwrap(),
        matrix_y: f[7].parse().unwrap(),
        divisor: if f[8] == "-" {
            None
        } else {
            Some(f[8].parse().unwrap())
        },
        bias: f[9].parse().unwrap(),
        edge: EdgeMode::from_upstream(f[10]),
        preserve_alpha: f[11] == "1",
        data: numbers(f[12], |value| value.parse().unwrap()),
        matrix: numbers(f[13], |value| value.parse().unwrap()),
        expected: numbers(f[14], |value| value.parse().unwrap()),
    }
}

#[test]
fn matches_upstream_byte_for_byte() {
    let fixture = include_str!("convolution-fixture.txt");
    let cases: Vec<Case> = fixture
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(parse)
        .collect();
    // A fixture that failed to load would make this test pass while comparing nothing.
    assert_eq!(cases.len(), 48, "every fixture case is read");

    for (index, case) in cases.iter().enumerate() {
        let source = RegionView {
            data: &case.data,
            bitmap_width: case.bitmap_width,
            bitmap_height: case.bitmap_height,
            x: case.x,
            y: case.y,
            width: case.width,
            height: case.height,
        };
        let mut out = vec![0u8; (case.width * case.height * 4) as usize];
        convolve_bitmap(
            &mut out,
            &source,
            &case.matrix,
            case.matrix_x,
            case.matrix_y,
            case.divisor,
            case.bias,
            case.edge,
            case.preserve_alpha,
        )
        .unwrap();
        assert_eq!(
            out,
            case.expected,
            "case {index}: {}x{} region {}x{} at ({},{}), {}x{} matrix, {:?} edge, preserve_alpha {}",
            case.bitmap_width,
            case.bitmap_height,
            case.width,
            case.height,
            case.x,
            case.y,
            case.matrix_x,
            case.matrix_y,
            case.edge,
            case.preserve_alpha,
        );
    }
}
