//! Replays alpha, morphological and pixelate cases whose expected bytes came from UPSTREAM'S OWN TypeScript.
//!
//! The companion to `convolution_differential.rs`, and it exists for the same measured reason: upstream's
//! hand-written cases use single-channel ramps and full-bitmap regions, where a channel mix-up or an off-by-one
//! in the clipping is invisible. These cases use random RGBA, regions offset to hang off the bitmap edge, and
//! radii and block sizes that leave partial windows.
//!
//! Regenerated by `packages/bitmap-wasm/src/fixturegen2.bench.test.ts`, which calls upstream directly.

use flighthq_bitmap_core::{
    Morphology, RegionView, RegionViewMut, apply_morphological, multiply_bitmap_alpha,
    pixelate_bitmap, set_bitmap_alpha,
};

struct Case {
    kind: String,
    bitmap_width: i32,
    bitmap_height: i32,
    x: i32,
    y: i32,
    width: i32,
    height: i32,
    parameter: f64,
    before: Vec<u8>,
    expected: Vec<u8>,
}

fn parse(line: &str) -> Case {
    let f: Vec<&str> = line.split(';').collect();
    assert_eq!(f.len(), 10, "fixture line has 10 fields: {line}");
    Case {
        kind: f[0].to_owned(),
        bitmap_width: f[1].parse().unwrap(),
        bitmap_height: f[2].parse().unwrap(),
        x: f[3].parse().unwrap(),
        y: f[4].parse().unwrap(),
        width: f[5].parse().unwrap(),
        height: f[6].parse().unwrap(),
        parameter: f[7].parse().unwrap(),
        before: f[8]
            .split(',')
            .map(|value| value.parse().unwrap())
            .collect(),
        expected: f[9]
            .split(',')
            .map(|value| value.parse().unwrap())
            .collect(),
    }
}

#[test]
fn matches_upstream_byte_for_byte() {
    let fixture = include_str!("kernel-fixture.txt");
    let cases: Vec<Case> = fixture
        .lines()
        .filter(|line| !line.starts_with('#') && !line.trim().is_empty())
        .map(parse)
        .collect();
    assert_eq!(cases.len(), 60, "every fixture case is read");

    let mut covered = std::collections::BTreeSet::new();
    for (index, case) in cases.iter().enumerate() {
        covered.insert(case.kind.clone());
        let actual = match case.kind.as_str() {
            // In-place kernels mutate the bitmap, so the comparison is the whole buffer afterwards.
            "setAlpha" | "multiplyAlpha" => {
                let mut data = case.before.clone();
                let mut view = RegionViewMut {
                    data: &mut data,
                    bitmap_width: case.bitmap_width,
                    bitmap_height: case.bitmap_height,
                    x: case.x,
                    y: case.y,
                    width: case.width,
                    height: case.height,
                };
                if case.kind == "setAlpha" {
                    set_bitmap_alpha(&mut view, case.parameter);
                } else {
                    multiply_bitmap_alpha(&mut view, case.parameter);
                }
                data
            }
            // Out-of-place kernels write a region-sized buffer.
            kind => {
                let source = RegionView {
                    data: &case.before,
                    bitmap_width: case.bitmap_width,
                    bitmap_height: case.bitmap_height,
                    x: case.x,
                    y: case.y,
                    width: case.width,
                    height: case.height,
                };
                let mut out = vec![0u8; (case.width * case.height * 4) as usize];
                match kind {
                    "dilate" => {
                        apply_morphological(&mut out, &source, case.parameter, Morphology::Dilate)
                    }
                    "erode" => {
                        apply_morphological(&mut out, &source, case.parameter, Morphology::Erode)
                    }
                    "pixelate" => pixelate_bitmap(&mut out, &source, case.parameter),
                    other => panic!("unknown fixture kind {other}"),
                }
                out
            }
        };
        assert_eq!(
            actual,
            case.expected,
            "case {index} ({}): {}x{} bitmap, region {}x{} at ({},{}), parameter {}",
            case.kind,
            case.bitmap_width,
            case.bitmap_height,
            case.width,
            case.height,
            case.x,
            case.y,
            case.parameter,
        );
    }

    // A fixture that silently stopped covering a kernel would leave this test passing on the others.
    assert_eq!(
        covered.into_iter().collect::<Vec<_>>(),
        vec!["dilate", "erode", "multiplyAlpha", "pixelate", "setAlpha"],
        "every mirrored kernel appears in the fixture",
    );
}
