import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import {
  assertBitmapWasmArtifactFresh,
  computeBitmapWasmInputHash,
  renderBitmapWasmBytes,
  assertWasmArtifactFresh,
  wasmArtifactTargets,
} from '../../tools/generator/src/wasm-artifact.ts';

it('keeps every committed wasm facade artifact fresh', () => {
  for (const target of Object.values(wasmArtifactTargets)) {
    expect(() => assertWasmArtifactFresh(path.resolve('.'), target), target.artifactPath).not.toThrow();
  }
});

describe('bitmap wasm artifact freshness', () => {
  let workspace: string;

  beforeEach(() => {
    workspace = mkdtempSync(path.join(tmpdir(), 'flight-rs-wasm-artifact-'));
    writeFixture(workspace);
  });

  afterEach(() => {
    rmSync(workspace, { force: true, recursive: true });
  });

  it('hashes the transitive local crate and packaging inputs deterministically', () => {
    const first = computeBitmapWasmInputHash(workspace);
    expect(computeBitmapWasmInputHash(workspace)).toBe(first);

    write(workspace, 'generated/crates/flighthq-bitmap/src/lib.rs', 'pub fn changed() {}\n');

    expect(computeBitmapWasmInputHash(workspace)).not.toBe(first);
  });

  it('accepts current generated bytes and rejects stale inputs or altered output', () => {
    const artifact = 'packages/bitmap-wasm/src/wasm/bitmapWasmBytes.ts';
    const rendered = renderBitmapWasmBytes(workspace, Uint8Array.from([1, 2, 3]));
    write(workspace, artifact, rendered);
    expect(() => assertBitmapWasmArtifactFresh(workspace)).not.toThrow();

    write(workspace, 'generated/crates/flighthq-bitmap/src/lib.rs', 'pub fn stale() {}\n');
    expect(() => assertBitmapWasmArtifactFresh(workspace)).toThrow(/stale Rust or packaging inputs/u);

    write(workspace, 'generated/crates/flighthq-bitmap/src/lib.rs', 'pub fn bitmap() {}\n');
    write(workspace, artifact, rendered.replace("'AQID'", "'AQIE'"));
    expect(() => assertBitmapWasmArtifactFresh(workspace)).toThrow(/recorded wasm output hash/u);

    write(workspace, artifact, rendered.replace('binary.length', 'binary.byteLength'));
    expect(() => assertBitmapWasmArtifactFresh(workspace)).toThrow(/canonical embedded module/u);
  });
});

function writeFixture(workspace: string): void {
  write(workspace, 'Cargo.lock', 'version = 4\n');
  write(workspace, 'Cargo.toml', '[workspace]\nresolver = "3"\n');
  write(workspace, 'rust-toolchain.toml', '[toolchain]\nchannel = "stable"\n');
  write(workspace, 'tools/generator/src/build-wasm.ts', 'export {};\n');
  write(workspace, 'packages/bitmap-wasm/scripts/embed-wasm.ts', 'export {};\n');
  write(
    workspace,
    'generated/crates/flighthq-bitmap-wasm/Cargo.toml',
    '[package]\nname = "flighthq-bitmap-wasm"\n[lib]\npath = "src/lib.rs"\n[dependencies]\nflighthq-bitmap = { path = "../flighthq-bitmap" }\n',
  );
  write(workspace, 'generated/crates/flighthq-bitmap-wasm/src/lib.rs', 'pub fn wasm() {}\n');
  write(
    workspace,
    'generated/crates/flighthq-bitmap/Cargo.toml',
    '[package]\nname = "flighthq-bitmap"\n[lib]\npath = "src/lib.rs"\n',
  );
  write(workspace, 'generated/crates/flighthq-bitmap/src/lib.rs', 'pub fn bitmap() {}\n');
}

function write(workspace: string, file: string, content: string): void {
  const absolute = path.join(workspace, file);
  mkdirSync(path.dirname(absolute), { recursive: true });
  writeFileSync(absolute, content);
}
