// The full `@flighthq/surface` API, drop-in compatible. Everything is
// re-exported unchanged except the bulk pixel ops below, which are overridden
// with wasm-backed implementations of identical signature (explicit named
// re-exports shadow the matching `export *` names). The analytical comparison
// utilities (compareSurface, getSurfaceMismatch, createSurfaceFingerprint) are
// not overridden and stay as the JS `@flighthq/surface` implementations.
export {
  applySurfaceColorTransform,
  applySurfacePaletteMap,
  applySurfaceThreshold,
  bevelSurface,
  blurSurfacePixelsHorizontal,
  blurSurfacePixelsHorizontalWeighted,
  blurSurfacePixelsVertical,
  blurSurfacePixelsVerticalWeighted,
  boxBlurSurface,
  colorMatrixSurface,
  compositeSurfacePixels,
  compositeSurfaceRegion,
  convertSurfacePixelOrder,
  convolveSurface,
  copySurfaceChannel,
  copySurfacePixels,
  dilateSurface,
  displaceSurface,
  dissolveSurfacePixels,
  dropShadowSurface,
  equalizeSurfaceHistogram,
  erodeSurface,
  extractSurfacePixels,
  extractSurfacePixels32,
  fillSurfaceNoise,
  fillSurfacePerlinNoise,
  fillSurfaceRectangle,
  flipSurfaceHorizontal,
  flipSurfaceVertical,
  floodFillSurface,
  gaussianBlurSurface,
  getSurfaceColorBoundsRectangle,
  getSurfaceCoverage,
  getSurfaceHistogram,
  glowSurface,
  gradientBevelSurface,
  gradientGlowSurface,
  initSurfaceRs,
  innerGlowSurface,
  innerShadowSurface,
  medianSurface,
  mergeSurface,
  pixelateSurface,
  premultiplySurfacePixels,
  resizeSurface,
  rotateSurface,
  rotateSurface180,
  rotateSurfaceClockwise,
  rotateSurfaceCounterClockwise,
  scrollSurface,
  sharpenSurface,
  unpremultiplySurfacePixels,
  writeSurfacePixels,
  writeSurfacePixels32,
} from './surfaceWasm';
export * from '@flighthq/surface';
