// The full upstream API remains available. Only functions present in the
// generator's selected, compiled bitmap slice are shadowed by wasm-backed
// implementations; every deferred function remains the cultivated TypeScript
// implementation until its source is admitted to generation.
export {
  applyBitmapCurve,
  applyBitmapLevels,
  applyBitmapPaletteMap,
  buildBitmapBrightnessColorMatrix,
  buildBitmapContrastColorMatrix,
  buildBitmapGrayscaleColorMatrix,
  buildBitmapHueRotationColorMatrix,
  buildBitmapInvertColorMatrix,
  buildBitmapSaturationColorMatrix,
  buildBitmapSepiaColorMatrix,
  colorMatrixBitmap,
  compareBitmapFingerprints,
  concatBitmapColorMatrix,
  convolveBitmap,
  copyBitmapAlpha,
  copyBitmapPixels,
  createBitmapFingerprint,
  dilateBitmap,
  erodeBitmap,
  fillBitmapNoise,
  fillBitmapPerlinNoise,
  fillBitmapRectangle,
  fillBitmapTurbulence,
  getBitmapColorBoundsRectangle,
  getBitmapCoverage,
  getBitmapHistogram,
  getBitmapMismatch,
  initBitmapWasm,
  mergeBitmapChannels,
  multiplyBitmapAlpha,
  pixelateBitmap,
  premultiplyBitmapPixels,
  setBitmapAlpha,
  setBitmapColorMatrixIdentity,
  unpremultiplyBitmapPixels,
} from './bitmapWasm';
export * from '@flighthq/bitmap';
