// Compile-time boundary for the filtered repository. Published consumers
// resolve these modules from the real @flighthq dependencies declared by this
// package; this local declaration keeps the blessed facade independently
// buildable without compiling the complete upstream monorepo.
//
// Each declaration below is a structural subset of the real upstream type: it
// names only the members this facade reads, and every member it does name must
// match upstream exactly, in the module upstream actually exports it from.
// A subset is safe because the facade only consumes these values; declaring a
// member upstream does not export is not, because that mistake reaches the
// published .d.ts and breaks consumers who typecheck it.
//
// `npm run typecheck:upstream` compiles the same sources against
// `upstream/packages/*` with this file excluded, which is what proves the two
// still agree. Do not edit this file without re-running it.

declare module '@flighthq/types' {
  export interface Bitmap {
    readonly data: Uint8ClampedArray<ArrayBuffer>;
    height: number;
    version: number;
    width: number;
  }

  export interface RectangleLike {
    height: number;
    width: number;
    x: number;
    y: number;
  }

  export interface BitmapFingerprint {
    readonly cells: Uint8Array;
    readonly gridSize: number;
  }

  export interface BitmapRegion {
    height: number;
    bitmap: Bitmap;
    width: number;
    x: number;
    y: number;
  }

  export interface BitmapHistogram {
    alpha: number[];
    blue: number[];
    green: number[];
    red: number[];
  }

  export interface BitmapMismatch {
    readonly fraction: number;
    readonly maxChannelDelta: number;
    readonly mismatchedPixels: number;
    readonly totalPixels: number;
  }

  export interface BitmapConvolutionOptions {
    bias?: number;
    edge?: 'clamp' | 'mirror' | 'transparent' | 'wrap';
    divisor?: number;
    matrix: ReadonlyArray<number>;
    matrixX: number;
    matrixY: number;
    preserveAlpha?: boolean;
  }
}

declare module '@flighthq/bitmap' {
  import type { Bitmap } from '@flighthq/types';

  export function invalidateBitmap(bitmap: Bitmap): void;
}
